services:
  database:
    platform: linux/amd64
    image: postgres:16.2
    environment:
      POSTGRES_USER: zelda
      POSTGRES_DB: zelda
      POSTGRES_PASSWORD: M6hzeBBQxdNi4eYVY6GD
    volumes:
      - zelda-pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "zelda"]
      interval: 5s
      timeout: 3s
      retries: 10

  webserver:
    platform: linux/amd64
    env_file:
      - .environ
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
    environment:
      - PGHOST=database
      - PGUSER=zelda
      - PGPASSWORD=M6hzeBBQxdNi4eYVY6GD
    ports:
      - "8000:8000"

volumes:
  zelda-pgdata:
