import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import zelda.lib.date_utils
import zelda.lib.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=zelda.lib.date_utils.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=zelda.lib.date_utils.now, editable=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "set_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARCHAIC_SET", "Archaic Set"),
                            ("ARMOR_OF_THE_DEPTHS_SET", "Armor Of The Depths Set"),
                            ("ARMOR_OF_THE_WILD", "Armor Of The Wild"),
                            ("AWAKENING_SET", "Awakening Set"),
                            ("BARBARIAN_SET", "Barbarian Set"),
                            ("CHARGED_SET", "Charged Set"),
                            ("CLIMBING_SET", "Climbing Set"),
                            ("DARK_SET", "Dark Set"),
                            ("DESERT_VOE_SET", "Desert Voe Set"),
                            ("EMBER_SET", "Ember Set"),
                            ("EVIL_SPIRIT_SET", "Evil Spirit Set"),
                            ("FIERCE_DEITY_SET", "Fierce Deity Set"),
                            ("FLAMEBREAKER_SET", "Flamebreaker Set"),
                            ("FROGGY_SET", "Froggy Set"),
                            ("FROSTBITE_SET", "Frostbite Set"),
                            ("GLIDE_SET", "Glide Set"),
                            ("HERO_SET", "Hero Set"),
                            ("HYLIAN_SET", "Hylian Set"),
                            ("MINER_SET", "Miner Set"),
                            ("MYSTIC_SET", "Mystic Set"),
                            ("PHANTOM_SET", "Phantom Set"),
                            ("RADIANT_SET", "Radiant Set"),
                            ("ROYAL_GUARD_SET", "Royal Guard Set"),
                            ("RUBBER_SET", "Rubber Set"),
                            ("SKY_SET", "Sky Set"),
                            ("SNOWQUILL_SET", "Snowquill Set"),
                            ("SOLDIERS_SET", "Soldiers Set"),
                            ("STEALTH_SET", "Stealth Set"),
                            ("TIME_SET", "Time Set"),
                            ("TINGLE_SET", "Tingle Set"),
                            ("TWILIGHT_SET", "Twilight Set"),
                            ("WIND_SET", "Wind Set"),
                            ("YIGA_SET", "Yiga Set"),
                            ("ZONAITE_SET", "Zonaite Set"),
                            ("ZORA_SET", "Zora Set"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "body_part_code",
                    models.CharField(
                        choices=[("HEAD", "Head"), ("BODY", "Body"), ("LEGS", "Legs")],
                        max_length=255,
                    ),
                ),
                ("max_level", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserArmor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=zelda.lib.date_utils.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=zelda.lib.date_utils.now, editable=False
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "armor",
                    zelda.lib.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_levels",
                        to="armor.armor",
                    ),
                ),
                (
                    "user",
                    zelda.lib.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="armor_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArmorUpgradeCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=zelda.lib.date_utils.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=zelda.lib.date_utils.now, editable=False
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                ("quantity", models.PositiveSmallIntegerField()),
                (
                    "item_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RUPEE", "Rupee"),
                            ("POE", "Poe"),
                            ("BUBBUL_GEM", "Bubbul Gem"),
                            ("ACORN", "Acorn"),
                            ("AEROCUDA_EYEBALL", "Aerocuda Eyeball"),
                            ("AEROCUDA_WING", "Aerocuda Wing"),
                            ("AMBER", "Amber"),
                            ("BLACK_BOKOBLIN_HORN", "Black Bokoblin Horn"),
                            ("BLACK_BOSS_BOKOBLIN_HORN", "Black Boss Bokoblin Horn"),
                            ("BLACK_HINOX_HORN", "Black Hinox Horn"),
                            ("BLACK_HORRIBLIN_HORN", "Black Horriblin Horn"),
                            ("BLACK_LIZALFOS_HORN", "Black Lizalfos Horn"),
                            ("BLADED_RHINO_BEETLE", "Bladed Rhino Beetle"),
                            ("BLUE_BOKOBLIN_HORN", "Blue Bokoblin Horn"),
                            ("BLUE_BOSS_BOKOBLIN_HORN", "Blue Boss Bokoblin Horn"),
                            ("BLUE_HORRIBLIN_HORN", "Blue Horriblin Horn"),
                            ("BLUE_LIZALFOS_HORN", "Blue Lizalfos Horn"),
                            ("BLUE_LIZALFOS_TAIL", "Blue Lizalfos Tail"),
                            ("BLUE_MOBLIN_HORN", "Blue Moblin Horn"),
                            ("BLUE_NIGHTSHADE", "Blue Nightshade"),
                            (
                                "BLUE_MANED_LYNEL_MACE_HORN",
                                " Blue-Maned Lynel Mace Horn",
                            ),
                            (
                                "BLUE_MANED_LYNEL_SABER_HORN",
                                " Blue-Maned Lynel Saber Horn",
                            ),
                            ("BLUE_WHITE_FROX_FANG", " Blue-White Frox Fang"),
                            ("BOKOBLIN_FANG", "Bokoblin Fang"),
                            ("BOKOBLIN_GUTS", "Bokoblin Guts"),
                            ("BOKOBLIN_HORN", "Bokoblin Horn"),
                            ("BOSS_BOKOBLIN_FANG", "Boss Bokoblin Fang"),
                            ("BOSS_BOKOBLIN_HORN", "Boss Bokoblin Horn"),
                            ("BRIGHTBLOOM_SEED", "Brightbloom Seed"),
                            ("BRIGHTCAP", "Brightcap"),
                            ("CAPTAIN_CONSTRUCT_I_HORN", "Captain Construct I Horn"),
                            ("CAPTAIN_CONSTRUCT_II_HORN", "Captain Construct Ii Horn"),
                            (
                                "CAPTAIN_CONSTRUCT_III_HORN",
                                "Captain Construct Iii Horn",
                            ),
                            ("CHILLFIN_TROUT", "Chillfin Trout"),
                            ("CHILLSHROOM", "Chillshroom"),
                            ("CHUCHU_JELLY", "Chuchu Jelly"),
                            ("COLD_DARNER", "Cold Darner"),
                            ("COOL_SAFFLINA", "Cool Safflina"),
                            ("COURSER_BEE_HONEY", "Courser Bee Honey"),
                            ("DARK_CLUMP", "Dark Clump"),
                            ("DAZZLEFRUIT", "Dazzlefruit"),
                            ("DEEP_FIREFLY", "Deep Firefly"),
                            ("DIAMOND", "Diamond"),
                            ("DINRAAL_S_CLAW", "Dinraal's Claw"),
                            ("DINRAAL_S_HORN", "Dinraal's Horn"),
                            ("DINRAAL_S_SCALE", "Dinraal's Scale"),
                            ("ELECTRIC_DARNER", "Electric Darner"),
                            ("ELECTRIC_KEESE_WING", "Electric Keese Wing"),
                            ("ELECTRIC_LIZALFOS_HORN", "Electric Lizalfos Horn"),
                            ("ELECTRIC_LIZALFOS_TAIL", "Electric Lizalfos Tail"),
                            ("ELECTRIC_SAFFLINA", "Electric Safflina"),
                            ("ENERGETIC_RHINO_BEETLE", "Energetic Rhino Beetle"),
                            ("FAROSH_S_CLAW", "Farosh's Claw"),
                            ("FAROSH_S_HORN", "Farosh's Horn"),
                            ("FAROSH_S_SCALE", "Farosh's Scale"),
                            ("FIRE_FRUIT", "Fire Fruit"),
                            ("FIRE_KEESE_WING", "Fire Keese Wing"),
                            ("FIRE_LIKE_STONE", "Fire Like Stone"),
                            ("FIRE_BREATH_LIZALFOS_HORN", "Fire-Breath Lizalfos Horn"),
                            ("FIRE_BREATH_LIZALFOS_TAIL", "Fire-Breath Lizalfos Tail"),
                            ("FIREPROOF_LIZARD", "Fireproof Lizard"),
                            ("FLINT", "Flint"),
                            ("FROX_FANG", "Frox Fang"),
                            ("FROX_FINGERNAIL", "Frox Fingernail"),
                            ("FROX_GUTS", "Frox Guts"),
                            ("GIANT_BRIGHTBLOOM_SEED", "Giant Brightbloom Seed"),
                            ("GIBDO_BONE", "Gibdo Bone"),
                            ("GIBDO_GUTS", "Gibdo Guts"),
                            ("GIBDO_WING", "Gibdo Wing"),
                            ("GLEEOK_FLAME_HORN", "Gleeok Flame Horn"),
                            ("GLEEOK_FROST_HORN", "Gleeok Frost Horn"),
                            ("GLEEOK_GUTS", "Gleeok Guts"),
                            ("GLEEOK_THUNDER_HORN", "Gleeok Thunder Horn"),
                            ("GLEEOK_WING", "Gleeok Wing"),
                            ("GLOWING_CAVE_FISH", "Glowing Cave Fish"),
                            ("HEARTY_BASS", "Hearty Bass"),
                            ("HEARTY_LIZARD", "Hearty Lizard"),
                            ("HIGHTAIL_LIZARD", "Hightail Lizard"),
                            ("HINOX_GUTS", "Hinox Guts"),
                            ("HINOX_TOENAIL", "Hinox Toenail"),
                            ("HINOX_TOOTH", "Hinox Tooth"),
                            ("HORRIBLIN_GUTS", "Horriblin Guts"),
                            ("HORRIBLIN_HORN", "Horriblin Horn"),
                            ("HOT_FOOTED_FROG", "Hot-Footed Frog"),
                            ("HYRULE_BASS", "Hyrule Bass"),
                            ("ICE_FRUIT", "Ice Fruit"),
                            ("ICE_KEESE_WING", "Ice Keese Wing"),
                            ("ICE_LIKE_STONE", "Ice Like Stone"),
                            ("ICE_BREATH_LIZALFOS_HORN", "Ice-Breath Lizalfos Horn"),
                            ("ICE_BREATH_LIZALFOS_TAIL", "Ice-Breath Lizalfos Tail"),
                            ("KEESE_EYEBALL", "Keese Eyeball"),
                            ("KEESE_WING", "Keese Wing"),
                            ("LARGE_ZONAI_CHARGE", "Large Zonai Charge"),
                            ("LARGE_ZONAITE", "Large Zonaite"),
                            ("LIGHT_DRAGON_S_HORN", "Light Dragon's Horn"),
                            ("LIGHT_DRAGON_S_SCALE", "Light Dragon's Scale"),
                            ("LIGHT_DRAGON_S_TALON", "Light Dragon's Talon"),
                            ("LIZALFOS_HORN", "Lizalfos Horn"),
                            ("LIZALFOS_TAIL", "Lizalfos Tail"),
                            ("LIZALFOS_TALON", "Lizalfos Talon"),
                            ("LUMINOUS_STONE", "Luminous Stone"),
                            ("LYNEL_GUTS", "Lynel Guts"),
                            ("LYNEL_HOOF", "Lynel Hoof"),
                            ("LYNEL_MACE_HORN", "Lynel Mace Horn"),
                            ("LYNEL_SABER_HORN", "Lynel Saber Horn"),
                            ("MIGHTY_BANANAS", "Mighty Bananas"),
                            ("MIGHTY_THISTLE", "Mighty Thistle"),
                            ("MOBLIN_FANG", "Moblin Fang"),
                            ("MOBLIN_GUTS", "Moblin Guts"),
                            ("MOBLIN_HORN", "Moblin Horn"),
                            ("MOLDUGA_FIN", "Molduga Fin"),
                            ("MOLDUGA_GUTS", "Molduga Guts"),
                            ("MOLDUGA_JAW", "Molduga Jaw"),
                            ("NAYDRA_S_HORN", "Naydra's Horn"),
                            ("NAYDRA_S_SCALE", "Naydra's Scale"),
                            ("OBSIDIAN_FROX_FANG", "Obsidian Frox Fang"),
                            ("OCTO_BALLOON", "Octo Balloon"),
                            ("OCTOROK_EYEBALL", "Octorok Eyeball"),
                            ("OCTOROK_TENTACLE", "Octorok Tentacle"),
                            ("OPAL", "Opal"),
                            ("PUFFSHROOM", "Puffshroom"),
                            ("RAZORCLAW_CRAB", "Razorclaw Crab"),
                            ("RAZORSHROOM", "Razorshroom"),
                            ("RED_CHUCHU_JELLY", "Red Chuchu Jelly"),
                            ("RUBY", "Ruby"),
                            ("RUSHROOM", "Rushroom"),
                            ("SAPPHIRE", "Sapphire"),
                            ("SHARD_OF_DINRAAL_S_FANG", "Shard of Dinraal's Fang"),
                            ("SHARD_OF_FAROSH_S_FANG", "Shard of Farosh's Fang"),
                            ("SHARD_OF_FAROSH_S_SPIKE", "Shard of Farosh's Spike"),
                            (
                                "SHARD_OF_LIGHT_DRAGON_S_FANG",
                                "Shard of Light Dragon's Fang",
                            ),
                            ("SHOCK_FRUIT", "Shock Fruit"),
                            ("SHOCK_LIKE_STONE", "Shock Like Stone"),
                            ("SILENT_PRINCESS", "Silent Princess"),
                            ("SILENT_SHROOM", "Silent Shroom"),
                            ("SILVER_BOKOBLIN_HORN", "Silver Bokoblin Horn"),
                            ("SILVER_BOSS_BOKOBLIN_HORN", "Silver Boss Bokoblin Horn"),
                            ("SILVER_LIZALFOS_HORN", "Silver Lizalfos Horn"),
                            ("SILVER_LYNEL_MACE_HORN", "Silver Lynel Mace Horn"),
                            ("SILVER_LYNEL_SABER_HORN", "Silver Lynel Saber Horn"),
                            ("SILVER_MOBLIN_HORN", "Silver Moblin Horn"),
                            ("SIZZLEFIN_TROUT", "Sizzlefin Trout"),
                            ("SMOTHERWING_BUTTERFLY", "Smotherwing Butterfly"),
                            ("SNEAKY_RIVER_SNAIL", "Sneaky River Snail"),
                            ("SOLDIER_CONSTRUCT_HORN", "Soldier Construct Horn"),
                            ("SOLDIER_CONSTRUCT_II_HORN", "Soldier Construct Ii Horn"),
                            (
                                "SOLDIER_CONSTRUCT_III_HORN",
                                "Soldier Construct Iii Horn",
                            ),
                            ("SOLDIER_CONSTRUCT_IV_HORN", "Soldier Construct Iv Horn"),
                            ("STAR_FRAGMENT", "Star Fragment"),
                            ("STEALTHFIN_TROUT", "Stealthfin Trout"),
                            ("STICKY_FROG", "Sticky Frog"),
                            ("STICKY_LIZARD", "Sticky Lizard"),
                            ("SUMMERWING_BUTTERFLY", "Summerwing Butterfly"),
                            ("SUNDELION", "Sundelion"),
                            ("SUNSET_FIREFLY", "Sunset Firefly"),
                            ("SUNSHROOM", "Sunshroom"),
                            ("SWIFT_CARROT", "Swift Carrot"),
                            ("SWIFT_VIOLET", "Swift Violet"),
                            ("THUNDERWING_BUTTERFLY", "Thunderwing Butterfly"),
                            ("TOPAZ", "Topaz"),
                            ("VOLTFIN_TROUT", "Voltfin Trout"),
                            ("VOLTFRUIT", "Voltfruit"),
                            ("WARM_DARNER", "Warm Darner"),
                            ("WARM_SAFFLINA", "Warm Safflina"),
                            ("WHITE_CHUCHU_JELLY", "White Chuchu Jelly"),
                            (
                                "WHITE_MANED_LYNEL_MACE_HORN",
                                "White-Maned Lynel Mace Horn",
                            ),
                            (
                                "WHITE_MANED_LYNEL_SABER_HORN",
                                "White-Maned Lynel Saber Horn",
                            ),
                            ("WINTERWING_BUTTERFLY", "Winterwing Butterfly"),
                            ("YELLOW_CHUCHU_JELLY", "Yellow Chuchu Jelly"),
                            ("ZAPSHROOM", "Zapshroom"),
                            ("ZONAITE", "Zonaite"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "armor",
                    zelda.lib.models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="armor.armor",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="armor",
            constraint=models.UniqueConstraint(
                fields=("set_code", "body_part_code"), name="unique_armor_set_body_part"
            ),
        ),
        migrations.AddConstraint(
            model_name="armorupgradecost",
            constraint=models.UniqueConstraint(
                fields=("armor", "level", "item_code"), name="unique_level_upgrade_cost"
            ),
        ),
    ]
